services:
  mysql:
    image: mysql:8.0
    container_name: seckill-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: seckill
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # 检测数据库可用性
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s 
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.2
    container_name: seckill-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", ""]

  seckill:
    image: golang:1.22
    container_name: seckill-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Shanghai
    working_dir: /app
    command: sh -c "go mod tidy && go build -o seckill ./cmd/main.go && ./seckill"